"""
Skill 发布器

- 把通过验证的 Skill 源码写到 `hyperbrain/skills/auto_generated/<hash>.py`
- 在 `generated_skills` 表登记
- 调用 SkillLoader.reload() 热加载
"""
from __future__ import annotations

import json
import os
import time
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional

from hyperbrain.hermes.common import get_hermes_logger

logger = get_hermes_logger("skill_publisher")


class SkillPublisher:
    """落盘 + 注册自动生成的 Skill"""

    def __init__(self, db, skill_loader, skills_root: Optional[Path] = None):
        self.db = db
        self.skill_loader = skill_loader
        self.skills_root = skills_root or Path(__file__).resolve().parents[2] / "skills"
        self.auto_dir = self.skills_root / "auto_generated"
        self.auto_dir.mkdir(parents=True, exist_ok=True)

    def publish(
        self,
        *,
        intent_key: str,
        skill_meta: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        返回 {success, file_path, skill_name}
        """
        skill_name: str = skill_meta.get("skill_name") or f"auto_{intent_key[:8]}"
        file_path = self.auto_dir / f"{skill_name}.py"

        # 1) 写盘
        header = (
            f'"""\nAUTO-GENERATED by Hermes at {time.strftime("%Y-%m-%d %H:%M:%S")}\n'
            f'intent_key: {intent_key}\n'
            f'description: {skill_meta.get("description","")}\n'
            f'"""\n'
        )
        try:
            file_path.write_text(
                header + skill_meta["source_code"], encoding="utf-8"
            )
        except Exception as e:  # noqa: BLE001
            logger.error(f"write file failed: {e}")
            return {"success": False, "error": str(e), "skill_name": skill_name}

        # 2) 登记 generated_skills
        try:
            with self.db._get_connection() as conn:  # type: ignore[attr-defined]
                conn.execute(
                    """
                    INSERT OR REPLACE INTO generated_skills
                        (skill_name, file_path, intent_key, status, last_attempt_at, metadata)
                    VALUES (?, ?, ?, 'active', CURRENT_TIMESTAMP, ?)
                    """,
                    (
                        skill_name,
                        str(file_path),
                        intent_key,
                        json.dumps(
                            {
                                "category": skill_meta.get("category", "other"),
                                "tags": skill_meta.get("tags", []),
                                "class_name": skill_meta.get("class_name", ""),
                            },
                            ensure_ascii=False,
                        ),
                    ),
                )
        except Exception as e:  # noqa: BLE001
            logger.warning(f"generated_skills register failed: {e}")

        # 3) 热加载
        loaded: List[str] = []
        if self.skill_loader is not None:
            try:
                loaded = self.skill_loader.reload(only_new=True) or []
            except Exception as e:  # noqa: BLE001
                logger.warning(f"reload failed: {e}")

        return {
            "success": True,
            "file_path": str(file_path),
            "skill_name": skill_name,
            "loaded": loaded,
        }

    def rollback(
        self,
        *,
        intent_key: str,
        skill_name: str,
        file_path: str,
        error: str,
    ) -> None:
        """验证失败时：删文件 + 把 generated_skills 标 failed。"""
        try:
            if os.path.exists(file_path):
                os.remove(file_path)
        except Exception as e:  # noqa: BLE001
            logger.warning(f"rollback delete failed: {e}")
        try:
            with self.db._get_connection() as conn:  # type: ignore[attr-defined]
                conn.execute(
                    """
                    INSERT OR REPLACE INTO generated_skills
                        (skill_name, file_path, intent_key, status, error_log, last_attempt_at)
                    VALUES (?, ?, ?, 'failed', ?, CURRENT_TIMESTAMP)
                    """,
                    (skill_name, file_path, intent_key, error[:2000]),
                )
        except Exception as e:  # noqa: BLE001
            logger.warning(f"rollback db update failed: {e}")
